name: apiverve_hangmanword
description: Hangman Word Generator provides random words for hangman games with category filtering and difficulty levels based on word length.
version: 1.1.14
homepage: https://apiverve.com/marketplace/hangmanword?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/hangmanword-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
