// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.HangmanWordGenerator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("words")]
        public Word[] Words { get; set; }

        [JsonProperty("count")]
        public long Count { get; set; }

        [JsonProperty("difficulty")]
        public string Difficulty { get; set; }

        [JsonProperty("category")]
        public string Category { get; set; }

        [JsonProperty("html")]
        public string Html { get; set; }
    }

    public partial class Word
    {
        [JsonProperty("word")]
        public string WordWord { get; set; }

        [JsonProperty("blanks")]
        public string Blanks { get; set; }

        [JsonProperty("length")]
        public long Length { get; set; }

        [JsonProperty("uniqueLetters")]
        public long UniqueLetters { get; set; }

        [JsonProperty("difficulty")]
        public string Difficulty { get; set; }

        [JsonProperty("category")]
        public string Category { get; set; }

        [JsonProperty("maxGuesses")]
        public long MaxGuesses { get; set; }
    }
}
